name: Maven Publish

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17 & Maven deploy
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install gpg secret key
      run: |
        # Install gpg secret key
        cat <(echo -e "${{ secrets.SIGNEDATWPS_GPG_PRIVATE_KEY }}") | gpg --batch --import
        # Verify gpg secret key
        gpg --list-secret-keys --keyid-format LONG

    - name: Build with Maven
      run: mvn -B -Dgpg.passphrase="${{ secrets.SIGNEDATWPS_GPG_PASSPHRASE }}" clean verify

    - name: Publish to Maven Central
      run: |
        echo "$SETTINGS_XML" > settings.xml
        mvn --no-transfer-progress --batch-mode -s settings.xml deploy
      shell: bash
      env:
        SETTINGS_XML: ${{ secrets.OSSRH_SETTINGS_XML }}