name: Maven Build

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: Install gpg secret key
      run: |
        # Install gpg secret key
        cat <(echo -e "${{ secrets.SIGNEDATWPS_GPG_PRIVATE_KEY }}") | gpg --batch --import
        # Verify gpg secret key
        gpg --list-secret-keys --keyid-format LONG

    - name: Build with Maven
      run: mvn -B -Dgpg.passphrase="${{ secrets.SIGNEDATWPS_GPG_PASSPHRASE }}" clean verify

    - name: Publish to Maven Central
      run: mvn --no-transfer-progress --batch-mode deploy
      env:
        MAVEN_USERNAME: ${{ secrets.SIGNEDATWPS_SONATYPE_OSSRH_USER }}
        MAVEN_PASSWORD: ${{ secrets.SIGNEDATWPS_SONATYPE_OSSRH_PASSWORD }}
